[package]
name = "tun-rs-uring-rx-repro"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
tokio = { version = "1", features = ["macros", "process", "rt-multi-thread", "time"] }
tun-rs = "2.8.3"

[target.'cfg(all(target_os = "linux", not(target_env = "ohos")))'.dependencies]
tun-rs-uring = { git = "https://github.com/xxoo/tun-rs-uring.git", rev = "0ae67af6fd47a64d82705a6aa88e770b7d161189", default-features = false, features = ["async_tokio"] }
